/**
 * Audio data model (AUDIO-owned). `public/audio/manifest.json` is generated by `scripts/audio/build.mjs`
 * from `scripts/audio/recipe.mjs`; the engine only reads it.
 */

/** Voice categories: each has a voice cap, a bus and a spatial model (see categories.ts). */
export type CategoryId =
  | 'ui' | 'stinger' | 'cannon' | 'weapon' | 'impact' | 'explosion' | 'pickup' | 'player' | 'boss' | 'world' | 'alert' | 'voice'
  | 'ambience';

export interface DuckSpec {
  /** Which bus dips: music, the ducked SFX sub-bus, or the ambience beds. */
  target: 'music' | 'sfx' | 'ambience';
  /** Depth in dB (negative). */
  depth: number;
  /** Seconds held at full depth after the attack. */
  hold: number;
  attack?: number;
  release?: number;
}

export interface CueDef {
  category: CategoryId;
  /** Variation files relative to /audio/ (random pick without immediate repeat). */
  files: string[];
  /** Linear gain applied on top of the loudness-normalized file. */
  gain: number;
  /** ± random pitch in semitones. */
  pitch?: number;
  /** ± random gain in dB. */
  gainJitter?: number;
  /** 0..100: voice-stealing priority (higher survives). */
  priority?: number;
  /** Minimum seconds between two triggers of this cue (extra triggers are merged/dropped). */
  minInterval?: number;
  /** Max triggers of this cue per update() frame. */
  maxPerFrame?: number;
  /** Looping bed (ambience). */
  loop?: boolean;
  /** Optional spatial overrides (metres). */
  ref?: number;
  maxDistance?: number;
  duck?: DuckSpec;
  /** Decode sample rate in Hz (speech and long beds; saves decoded memory). */
  rate?: number;
  /** Human description for the lab / ledger. */
  desc?: string;
}

export interface MusicDef {
  file: string;
  gain: number;
  /** Tempo metadata for bar-synced transitions (estimated when not published). */
  bpm?: number;
  beatsPerBar?: number;
  /** Seconds of the first downbeat. */
  offset?: number;
  loop: boolean;
  /** File loops sample-seamlessly: use the element's native loop. */
  seamless?: boolean;
  /** Loop region for non-seamless tracks (crossfaded with a second element). */
  loopStart?: number;
  loopEnd?: number;
  loopCrossfade?: number;
  desc?: string;
}

export interface FileMeta {
  bytes: number;
  sha256: string;
  duration: number;
  channels: number;
  lufs: number | null;
  truePeak: number | null;
  sources: string[];
}

export interface AudioManifest {
  version: 1;
  generated?: string;
  cues: Record<string, CueDef>;
  music: Record<string, MusicDef>;
  files?: Record<string, FileMeta>;
}

/** Options for a single cue trigger. */
export interface PlayOptions {
  /** World position (metres); omitted = non-spatial (centre, full level). */
  x?: number;
  z?: number;
  /** Seconds from now (scheduled on the audio clock). */
  delay?: number;
  /** Linear gain multiplier. */
  gain?: number;
  /** Semitone offset (added to the random jitter). */
  pitch?: number;
  /** Extra priority for voice stealing. */
  priority?: number;
  /** Force a variation index. */
  variant?: number;
  /** Ignore minInterval (layers scheduled by the router). */
  force?: boolean;
  /** Play on another category's voices and bus (e.g. an incoming-shell whistle promoted to 'alert'). */
  category?: CategoryId;
}
