"""Build the offline source-asset review from unedited engine screenshots and provenance."""
import argparse, hashlib, html, json, pathlib, shutil
root=pathlib.Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser();parser.add_argument('--pass-number',default='23');args=parser.parse_args()
number=args.pass_number
source=root/'output/asset-gauntlet'/('in-world-'+number)
receipt=json.loads((source/'receipt.json').read_text())
manifest=json.loads((root/'public/assets/sketchfab/manifest.json').read_text())
out=root/'docs/overhaul/assets-gallery';(out/'media').mkdir(parents=True,exist_ok=True)
shutil.copyfile(root/'docs/art-direction/approved-direction-A.png',out/'media/target-A.png')
items=[];proof=[];escape=lambda value:html.escape(str(value),quote=True)
for record in receipt:
 kind=record['kind'];entry=next(m for m in manifest['ships'] if m['kind']==kind)
 assert not record['errors']
 assert any(a['kind']==kind and a['status']=='ready' and a['source']=='sketchfab' for a in record['assets'])
 name=kind+'.png';original=source/name;shutil.copyfile(original,out/'media'/name)
 proof.append({'kind':kind,'sourceUid':entry['uid'],'imageSha256':hashlib.sha256(original.read_bytes()).hexdigest(),'engineCapture':True,'edited':False})
 crew=next(a['crew'] for a in record['assets'] if a['id']==record['state']['playerId'])
 label=kind.replace('-',' ').title()
 items.append(f'<article id="{kind}"><div class="label">ACTUAL ENGINE · BUILD {escape(number)}</div><h2>{escape(label)}</h2><a href="media/{name}"><img src="media/{name}" alt="Actual in-game {escape(label)} screenshot" loading="lazy"></a><p>{escape(entry["title"])} · {escape(entry["author"])} · {len(crew)} visible-source crew instances in the scene</p><p><a href="{escape(entry["source"])}">Source model</a> · <a href="{escape(entry["license"]["url"])}">{escape(entry["license"]["label"])}</a></p></article>')
(out/'manifest.json').write_text(json.dumps({'build':number,'images':proof,'note':'Unedited engine screenshots. Stills do not establish performance or hidden geometry.'},indent=2)+'\n')
(out/'index.html').write_text('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The downloaded fleet · Art review</title><style>*{box-sizing:border-box}body{margin:0;background:#091a2a;color:#eaf1ef;font:16px/1.55 system-ui}main{max-width:1440px;margin:auto;padding:48px 28px}a{color:#ffce73}h1{font-size:clamp(38px,5vw,72px);line-height:1.05;letter-spacing:-.045em;max-width:900px}h2{font-size:28px;margin:.3em 0 .7em}.label{color:#ffce73;font-size:12px;letter-spacing:.14em}p{max-width:960px;color:#c3d0d8}.status{border-left:3px solid #ffbc6d;padding:12px 18px;background:#122b3d;margin:28px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:32px}article{padding:20px;background:#11283a;border:1px solid #284153;border-radius:14px}img{display:block;width:100%;height:auto;border-radius:6px}.target{max-width:900px;margin:40px 0 52px}.target img{max-height:580px;object-fit:contain;object-position:left}footer{margin:48px 0 0;border-top:1px solid #284153;padding-top:24px}@media(max-width:800px){main{padding:28px 16px}.grid{grid-template-columns:1fr}article{padding:14px}}</style></head><body><main><div class="label">WE ARE ON THE CRUISE / ASSET CORRECTION</div><h1>The downloaded fleet, in the actual game.</h1><p>Six complete Sketchfab ships and four downloaded character models replace the generated ship kit. Each image below is an unedited engine capture; click it for full resolution. The approved illustration is shown separately.</p><div class="status"><strong>Art acceptance remains open.</strong><br>Source integration and measured performance do not establish cinematic-anime parity. Read the independent critic and the current implementation review for the remaining gaps.</div><p><a href="../IMPLEMENTATION-REVIEW.md">Current review and measured evidence</a> · <a href="../evidence/critic-assets-23.md">Fresh blind visual review</a> · <a href="../../../ASSET-LICENSES.md">Creators, licenses and acquisition coverage</a> · <a href="manifest.json">Image hashes</a></p><figure class="target"><div class="label">GENERATED TARGET · APPROVED DIRECTION A</div><h2>Cinematic anime reference</h2><a href="media/target-A.png"><img src="media/target-A.png" alt="Approved cinematic anime concept illustration"></a><figcaption>Target illustration. This is not an engine screenshot.</figcaption></figure><section class="grid">'''+''.join(items)+'''</section><footer><p>Geometry, source maps and character rigs come from the credited downloads. The source archive contains additional acquired models that are not integrated. No claim of all assets completed, AAA quality, physical-mobile acceptance or Production promotion is made.</p></footer></main></body></html>''')
print('Built',len(items),'source-verified, unedited engine comparisons.')
